# Generated by Django 5.1.3 on 2024-11-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.TextField()),
                ('senha', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
