# Generated by Django 5.1.3 on 2024-11-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_pedido_alter_cliente_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='pedido',
            new_name='escolha',
        ),
    ]
