# Generated by Django 5.1.3 on 2024-11-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_rename_opcao_escolhida_cliente_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='pedido_cliente',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
