# Generated by Django 5.1.3 on 2024-11-09 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_cliente_pedido_alter_cliente_email'),
        ('pedido', '0002_alter_pedido_data_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='cliente.cliente'),
            preserve_default=False,
        ),
    ]
