# Generated by Django 5.1.3 on 2024-11-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_remove_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='pedido',
        ),
    ]
